# Generated by Django 4.2.10 on 2026-03-12 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Username в Telegram')),
                ('verification_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Код для привязки')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Telegram подтвержден')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Telegram профиль',
                'verbose_name_plural': 'Telegram профили',
                'db_table': 'bot_telegram_profiles',
            },
        ),
    ]
