# Generated by Django 5.2.10 on 2026-01-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusballet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('duration', models.IntegerField(default=60, help_text='Продолжительность занятия в минутах', verbose_name='Длительность (минуты)')),
                ('max_seats', models.IntegerField(default=10, verbose_name='Максимальное количество мест')),
                ('booked_seats', models.IntegerField(default=0, verbose_name='Занято мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно для записи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rusballet_app.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
