# Generated by Django 4.2.10 on 2026-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusballet_app', '0004_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Отмечать, если это пробное занятие (доступно для записи через бота/сайт)', verbose_name='Пробное занятие'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'date', 'start_time')},
        ),
    ]
