# Generated by Django 4.2.10 on 2026-03-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusballet_app', '0005_schedule_is_trial_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='age_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='group',
            name='age_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный возраст'),
        ),
    ]
