# Generated by Django 4.2.10 on 2026-03-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusballet_app', '0007_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(blank=True, help_text='Возраст ученика (для контроля выпуска)', null=True, verbose_name='Возраст'),
        ),
    ]
